"""
Normalize outbound outreach copy before validation, storage, and SMTP send.

Removes internal pipeline markers accidentally produced by LLM or legacy
fallback prefixes so recipients never see meta-language like "[DRAFT NEEDED]".
"""

from __future__ import annotations

import re

# Bracket/tag markers and internal prefixes (case-insensitive removal)
_MARKER_PATTERNS: tuple[str, ...] = (
    "[draft needed]",
    "[needs review]",
    "[pending review]",
    "[draft]",
    "[todo]",
    "[ai generated]",
    "[auto-generated]",
    "[template]",
)

# Lines containing these fragments are dropped when preparing mail for send only
_INTERNAL_LINE_HINTS: tuple[str, ...] = (
    "pending review",
    "awaiting review",
    "awaiting approval",
    "draft status",
    "this is a draft",
    "automated outreach",
    "ai generated",
    "generated by ai",
    "[draft",
)


def strip_bracket_subject_prefix(subject: str) -> str:
    """Remove leading [TAG] style prefixes from subject lines."""
    s = subject.strip()
    while True:
        m = re.match(r"^\[[^\]]{1,40}\]\s*", s, re.IGNORECASE)
        if not m:
            break
        s = s[m.end() :].strip()
    return s


def _apply_markers(text: str) -> str:
    t = text.strip()
    for marker in _MARKER_PATTERNS:
        t = re.sub(re.escape(marker), "", t, flags=re.IGNORECASE)
    return re.sub(r"[ \t]{2,}", " ", t).strip()


def clean_outreach_copy(subject: str, body: str, *, for_send: bool = False) -> tuple[str, str]:
    """
    Normalize subject/body whitespace and strip internal markers.

    When ``for_send`` is True, removes whole lines that look like internal
    workflow notes so they never reach the recipient.
    """
    s = strip_bracket_subject_prefix(_apply_markers(subject))
    b = _apply_markers(body)
    if for_send:
        kept: list[str] = []
        for line in b.splitlines():
            low = line.lower().strip()
            if not low:
                kept.append("")
                continue
            if any(h in low for h in _INTERNAL_LINE_HINTS):
                continue
            kept.append(line.rstrip())
        # Collapse trailing/leading empties but keep paragraph breaks
        b = "\n".join(kept).strip()
        while "\n\n\n" in b:
            b = b.replace("\n\n\n", "\n\n")
    s = re.sub(r"\s+", " ", s).strip()
    b = re.sub(r"\n{3,}", "\n\n", b).strip()
    return s[:80], b[:20000]
